Add focuspoint gravity to imgproxy url if focusArea is present in processing configuration
somehow-digital/typo3-media-processing pull request #10
Opened 2024-04-25 10:18 UTC by rtp-cgs

Related Issue: https://github.com/somehow-digital/typo3-media-processing/issues/9

Hello, as mentioned in the issue a few weeks ago I prepared a pull request which passes down the focuspoint from the processing configuration to the imgproxy url.

Please let me know what you think about this and if you wan't me to do any optimizations. It would be great if this change could make it to your package.

Regards,
Cyrill

2024-04-25 19:40 UTC, thasmo requested changes
Thank you for writing the PR! :)

Have some feedback, nothing major tho.

2024-04-25 19:40 UTC, thasmo commented on Classes/ImageService/ImgProxyImageService.php
> +
Just to be in line with the other conditions, I'd prefer to have this not defining a separate variable. Also, I'm not sure that we need the type casting.

```suggestion
		if (isset($configuration['focusArea']) && !$configuration['focusArea']->isEmpty()) {
			$horizontalOffset = FocusAreaUtility::calculateCenter(
				$configuration['focusArea']->getOffsetLeft(),
				$configuration['focusArea']->getWidth(),
			);

			$verticalOffset = FocusAreaUtility::calculateCenter(
				$configuration['focusArea']->getOffsetTop(),
				$configuration['focusArea']->getHeight(),
			);

			$uri->setGravity('fp', $horizontalOffset, $verticalOffset);
		}

```

2024-04-25 19:40 UTC, thasmo commented on Classes/Utility/FocusAreaUtility.php
> +}
Just to be consistent with the codebase, I'd prefer to not have doc blocks. Also, the comment is mostly superfluous due to the line being easy to read, I think.

```suggestion
class FocusAreaUtility
{
	public static function calculateCenter(float $offset, float $size)
	{
		return max(($offset + ($size / 2)), 0);
	}
}
```

2024-04-25 19:40 UTC, thasmo commented on Classes/UriBuilder/ImgProxyUri.php
> +		$this->gravity = [$type, $horizontalOffset, $verticalOffset];
Did you remove the array_filter for a reason? Can't remember exactly, but I think it fixed something; could be wrong, tho.

2024-04-29 08:01 UTC, rtp-cgs commented on Classes/UriBuilder/ImgProxyUri.php
> +		$this->gravity = [$type, $horizontalOffset, $verticalOffset];
If the $horizontalOffset or $verticalOffset was 0 then it was filtered out, resulting in an invalid imgproxy url.

2024-04-29 11:40 UTC, rtp-cgs commented
Hi, thanks for the fast response that is awesome.

I totally agree with your suggestions and just pushed them to the branch.

2024-04-29 12:12 UTC, thasmo approved these changes

2024-04-29 12:28 UTC, thasmo commented
Thank you for your contribution!

Going to merge this soon, and I will also probably take a look at implementing the focal point/area feature for other services/libraries as well, if I find some time. I'd like to have this feature supported for all relevant services for v1.

2024-04-30 14:35 UTC, merged